version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_KEYCLOAK_URL=${NEXT_PUBLIC_KEYCLOAK_URL}
        - NEXT_PUBLIC_KEYCLOAK_REALM=${NEXT_PUBLIC_KEYCLOAK_REALM}
        - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=${NEXT_PUBLIC_KEYCLOAK_CLIENT_ID}
        - NEXT_PUBLIC_UI_REDIRECT_URL=${NEXT_PUBLIC_UI_REDIRECT_URL}
        - NEXT_PUBLIC_KEYCLOAK_API_REMOTE_URL=${NEXT_PUBLIC_KEYCLOAK_API_REMOTE_URL}
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      PORT: "5001"
      ENABLE_HTTPS: "false"
    volumes:
      - ./ssl:/certs:ro
    ports:
      - "5001:5001"
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true