services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shared_network
    restart: unless-stopped

networks:
  shared_network:
    external: true